name: Web CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Frontend deps
        working-directory: frontend
        run: |
          npm ci
          npm run build
      - name: Docker build (smoke)
        run: docker compose build
